name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Configure Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Gradle project
        run: ./gradlew build

      - name: Compile Kotlin scripts
        run: |
          find scripts/ -name "*.kts" -print0 | while read -d $'\0' file
          do
              echo "Compiling $file..."
              kotlin "$file"
          done
