name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Configure Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew build
        
